#!/bin/sh
#
# To enable this hook, copy/symlink this file to ".git/hooks/pre-commit".
#  mklink .git\hooks\pre-commit ..\..\BuildTools\pre-commit

set -eu

DOTNET_FORMAT_VERSION=8.3.546805
DOTNET_PATH="$LOCALAPPDATA/ICSharpCode/ILSpy/dotnet-format-$DOTNET_FORMAT_VERSION"
if [ ! -d "$DOTNET_PATH" ]; then
 echo "Downloading dotnet-format $DOTNET_FORMAT_VERSION..."
 dotnet tool install --tool-path "$DOTNET_PATH" dotnet-format --version "$DOTNET_FORMAT_VERSION" --add-source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json"
fi

"$DOTNET_PATH/dotnet-format.exe" --version
if [ "${1:-}" = "--format" ]; then
	# called via format.bat
	"$DOTNET_PATH/dotnet-format.exe" whitespace --no-restore --verbosity detailed ILSpy.sln
elif git diff --quiet --ignore-submodules; then
	"$DOTNET_PATH/dotnet-format.exe" whitespace --no-restore --verbosity detailed ILSpy.sln
	git add -u -- \*\*.cs
else
	echo Partial commit: only verifying formatting
	exec "$DOTNET_PATH/dotnet-format.exe" whitespace --verify-no-changes --no-restore --verbosity detailed ILSpy.sln
fi
