// Copyright (c) 2026 AlphaSierraPapa for the SharpDevelop Team
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files (the "Software"), to deal in the Software
// without restriction, including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
// to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.CSharp.ProjectDecompiler;
using ICSharpCode.Decompiler.DebugInfo;
using ICSharpCode.Decompiler.Metadata;
using ICSharpCode.ILSpy.Properties;
using ICSharpCode.ILSpyX;
using ICSharpCode.ILSpyX.TreeView;

using ICSharpCode.ILSpy.AppEnv;
using ICSharpCode.ILSpy.Docking;
using ICSharpCode.ILSpy.TextView;
using ICSharpCode.ILSpy.TreeNodes;
using ICSharpCode.ILSpy.Util;

namespace ICSharpCode.ILSpy.Commands
{
	/// <summary>
	/// Shared "Generate Portable PDB" logic behind both the File-menu command and the
	/// assembly-node context-menu entry: pick an output folder, then run
	/// <see cref="PortablePdbWriter"/> for every selected assembly that carries a CodeView
	/// debug-directory entry. The per-file report (success / fail / total elapsed time) lands
	/// in a dedicated frozen tab via <see cref="DockWorkspace.RunInNewTabAsync"/>.
	/// </summary>
	internal static class PdbGenerator
	{
		/// <summary>
		/// Picks the valid loaded assemblies out of <paramref name="nodes"/>. PDB generation is
		/// gated further on the CodeView debug-directory entry at write time, so unsupported ones
		/// are still surfaced (not silently dropped) by <see cref="GenerateAsync"/>.
		/// </summary>
		public static bool TryGetAssemblies(IReadOnlyList<SharpTreeNode>? nodes, out LoadedAssembly[] assemblies)
		{
			assemblies = nodes?.OfType<AssemblyTreeNode>()
				.Where(n => n.LoadedAssembly.IsLoadedAsValidAssembly)
				.Select(n => n.LoadedAssembly)
				.ToArray() ?? [];
			return assemblies.Length > 0;
		}

		public static async Task GenerateAsync(LoadedAssembly[] assemblies, DockWorkspace dockWorkspace)
		{
			// First pass: classify assemblies. Only those with a CodeView debug-directory
			// entry can have a portable PDB generated by the writer; surface unsupported
			// ones in the report rather than silently skipping.
			var supported = new Dictionary<LoadedAssembly, PEFile>();
			var unsupported = new List<LoadedAssembly>();
			foreach (var a in assemblies)
			{
				try
				{
					if (a.GetMetadataFileOrNull() is PEFile file && PortablePdbWriter.HasCodeViewDebugDirectoryEntry(file))
						supported.Add(a, file);
					else
						unsupported.Add(a);
				}
				catch
				{
					unsupported.Add(a);
				}
			}
			if (supported.Count == 0)
			{
				// Surface the failure via ShowText rather than a MessageBox -- keeps the UX
				// consistent with the rest of the long-running command surface.
				var fail = new AvaloniaEditTextOutput { Title = "Generate Portable PDB" };
				fail.Write(string.Format(Resources.CannotCreatePDBFile,
					":" + Environment.NewLine + string.Join(Environment.NewLine, unsupported.Select(u => Path.GetFileName(u.FileName)))));
				fail.WriteLine();
				dockWorkspace.ShowText(fail);
				return;
			}

			var folder = await FilePickers.PickFolderAsync(Resources.SelectPDBOutputFolder);
			if (string.IsNullOrEmpty(folder))
				return;

			// GeneratingPortablePDB is a "...for {0}..." format string; fill the placeholder with the
			// single assembly's name, or a count when several were selected, so the tab title isn't a
			// literal "{0}".
			string title = supported.Count == 1
				? string.Format(Resources.GeneratingPortablePDB, supported.Keys.First().ShortName)
				: string.Format(Resources.GeneratingPortablePDB, supported.Count + " assemblies");

			// The PDB embeds decompiled sources, so honor the user's current decompiler settings
			// (snapshot once; the generation runs off the UI thread).
			var settings = AppComposition.TryGetExport<SettingsService>()?.CreateEffectiveDecompilerSettings()
				?? new DecompilerSettings();

			// Run in a dedicated frozen tab so browsing the tree while PDBs generate can't cancel it.
			await dockWorkspace.RunInNewTabAsync(title, token => Task.Run(() => {
				var output = new AvaloniaEditTextOutput { Title = "Generate Portable PDB" };
				var totalWatch = Stopwatch.StartNew();
				foreach (var (assembly, file) in supported)
				{
					var pdbFileName = Path.Combine(folder, WholeProjectDecompiler.CleanUpFileName(assembly.ShortName, ".pdb"));
					try
					{
						using var stream = new FileStream(pdbFileName, FileMode.Create, FileAccess.Write);
						var resolver = assembly.GetAssemblyResolver();
						var decompiler = new CSharpDecompiler(file, resolver, settings) {
							CancellationToken = token,
						};
						new PortablePdbWriter().WritePdb(file, decompiler, settings, stream);
						output.Write(string.Format(Resources.GeneratedPDBFile, pdbFileName));
						output.WriteLine();
					}
					catch (OperationCanceledException)
					{
						output.WriteLine();
						output.Write(Resources.GenerationWasCancelled);
						output.WriteLine();
						throw;
					}
					catch (Exception ex)
					{
						output.Write(string.Format(Resources.GenerationFailedForAssembly, assembly.FileName, ex.Message));
						output.WriteLine();
						output.WriteExceptionDetails(ex);
					}
				}
				totalWatch.Stop();
				output.WriteLine();
				output.Write(string.Format(Resources.GenerationCompleteInSeconds, totalWatch.Elapsed.TotalSeconds.ToString("F1")));
				output.WriteLine();
				output.WriteLine();
				output.AddOpenFolderButton(folder);
				return output;
			}, token)).ConfigureAwait(true);
		}

	}
}
