//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSharpCode.Decompiler.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICSharpCode.Decompiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Allow extension &apos;Add&apos; methods in collection initializer expressions 的本地化字符串。
        /// </summary>
        public static string AllowExtensionAddMethodsInCollectionInitializerExpressions {
            get {
                return ResourceManager.GetString("AllowExtensionAddMethodsInCollectionInitializerExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always cast targets of explicit interface implementation calls 的本地化字符串。
        /// </summary>
        public static string AlwaysCastTargetsOfExplicitInterfaceImplementationCalls {
            get {
                return ResourceManager.GetString("AlwaysCastTargetsOfExplicitInterfaceImplementationCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always use braces 的本地化字符串。
        /// </summary>
        public static string AlwaysUseBraces {
            get {
                return ResourceManager.GetString("AlwaysUseBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Windows Runtime projections on loaded assemblies 的本地化字符串。
        /// </summary>
        public static string ApplyWindowsRuntimeProjectionsOnLoadedAssemblies {
            get {
                return ResourceManager.GetString("ApplyWindowsRuntimeProjectionsOnLoadedAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array initializer expressions 的本地化字符串。
        /// </summary>
        public static string ArrayInitializerExpressions {
            get {
                return ResourceManager.GetString("ArrayInitializerExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C# 7.0 local functions are not implemented! 的本地化字符串。
        /// </summary>
        public static string C70LocalFunctionsAreNotImplemented {
            get {
                return ResourceManager.GetString("C70LocalFunctionsAreNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile ?. and ?[] operators 的本地化字符串。
        /// </summary>
        public static string DecompileAndOperators {
            get {
                return ResourceManager.GetString("DecompileAndOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile anonymous methods/lambdas 的本地化字符串。
        /// </summary>
        public static string DecompileAnonymousMethodsLambdas {
            get {
                return ResourceManager.GetString("DecompileAnonymousMethodsLambdas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile anonymous types 的本地化字符串。
        /// </summary>
        public static string DecompileAnonymousTypes {
            get {
                return ResourceManager.GetString("DecompileAnonymousTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile async methods 的本地化字符串。
        /// </summary>
        public static string DecompileAsyncMethods {
            get {
                return ResourceManager.GetString("DecompileAsyncMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile automatic events 的本地化字符串。
        /// </summary>
        public static string DecompileAutomaticEvents {
            get {
                return ResourceManager.GetString("DecompileAutomaticEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile automatic properties 的本地化字符串。
        /// </summary>
        public static string DecompileAutomaticProperties {
            get {
                return ResourceManager.GetString("DecompileAutomaticProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile await in catch/finally blocks 的本地化字符串。
        /// </summary>
        public static string DecompileAwaitInCatchFinallyBlocks {
            get {
                return ResourceManager.GetString("DecompileAwaitInCatchFinallyBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile C# 1.0 &apos;public unsafe fixed int arr[10];&apos; members 的本地化字符串。
        /// </summary>
        public static string DecompileC10PublicUnsafeFixedIntArr10Members {
            get {
                return ResourceManager.GetString("DecompileC10PublicUnsafeFixedIntArr10Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile [DecimalConstant(...)] as simple literal values 的本地化字符串。
        /// </summary>
        public static string DecompileDecimalConstantAsSimpleLiteralValues {
            get {
                return ResourceManager.GetString("DecompileDecimalConstantAsSimpleLiteralValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile enumerators (yield return) 的本地化字符串。
        /// </summary>
        public static string DecompileEnumeratorsYieldReturn {
            get {
                return ResourceManager.GetString("DecompileEnumeratorsYieldReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile expression trees 的本地化字符串。
        /// </summary>
        public static string DecompileExpressionTrees {
            get {
                return ResourceManager.GetString("DecompileExpressionTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile use of the &apos;dynamic&apos; type 的本地化字符串。
        /// </summary>
        public static string DecompileUseOfTheDynamicType {
            get {
                return ResourceManager.GetString("DecompileUseOfTheDynamicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect foreach statements 的本地化字符串。
        /// </summary>
        public static string DetectForeachStatements {
            get {
                return ResourceManager.GetString("DetectForeachStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect lock statements 的本地化字符串。
        /// </summary>
        public static string DetectLockStatements {
            get {
                return ResourceManager.GetString("DetectLockStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect switch on string 的本地化字符串。
        /// </summary>
        public static string DetectSwitchOnString {
            get {
                return ResourceManager.GetString("DetectSwitchOnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect tuple comparisons 的本地化字符串。
        /// </summary>
        public static string DetectTupleComparisons {
            get {
                return ResourceManager.GetString("DetectTupleComparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect using statements 的本地化字符串。
        /// </summary>
        public static string DetectUsingStatements {
            get {
                return ResourceManager.GetString("DetectUsingStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dictionary initializer expressions 的本地化字符串。
        /// </summary>
        public static string DictionaryInitializerExpressions {
            get {
                return ResourceManager.GetString("DictionaryInitializerExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F#-specific options 的本地化字符串。
        /// </summary>
        public static string FSpecificOptions {
            get {
                return ResourceManager.GetString("FSpecificOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include XML documentation comments in the decompiled code 的本地化字符串。
        /// </summary>
        public static string IncludeXMLDocumentationCommentsInTheDecompiledCode {
            get {
                return ResourceManager.GetString("IncludeXMLDocumentationCommentsInTheDecompiledCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert using declarations 的本地化字符串。
        /// </summary>
        public static string InsertUsingDeclarations {
            get {
                return ResourceManager.GetString("InsertUsingDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Introduce local functions (NOT IMPLEMENTED!) 的本地化字符串。
        /// </summary>
        public static string IntroduceLocalFunctionsNOTIMPLEMENTED {
            get {
                return ResourceManager.GetString("IntroduceLocalFunctionsNOTIMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsByRefLikeAttribute should be replaced with &apos;ref&apos; modifiers on structs 的本地化字符串。
        /// </summary>
        public static string IsByRefLikeAttributeShouldBeReplacedWithRefModifiersOnStructs {
            get {
                return ResourceManager.GetString("IsByRefLikeAttributeShouldBeReplacedWithRefModifiersOnStructs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsReadOnlyAttribute should be replaced with &apos;readonly&apos;/&apos;in&apos; modifiers on structs/parameters 的本地化字符串。
        /// </summary>
        public static string IsReadOnlyAttributeShouldBeReplacedWithReadonlyInModifiersOnStructsParameters {
            get {
                return ResourceManager.GetString("IsReadOnlyAttributeShouldBeReplacedWithReadonlyInModifiersOnStructsParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsUnmanagedAttribute on type parameters should be replaced with &apos;unmanaged&apos; constraints 的本地化字符串。
        /// </summary>
        public static string IsUnmanagedAttributeOnTypeParametersShouldBeReplacedWithUnmanagedConstraints {
            get {
                return ResourceManager.GetString("IsUnmanagedAttributeOnTypeParametersShouldBeReplacedWithUnmanagedConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nullable reference types 的本地化字符串。
        /// </summary>
        public static string NullableReferenceTypes {
            get {
                return ResourceManager.GetString("NullableReferenceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object/collection initializer expressions 的本地化字符串。
        /// </summary>
        public static string ObjectCollectionInitializerExpressions {
            get {
                return ResourceManager.GetString("ObjectCollectionInitializerExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove dead and side effect free code (use with caution!) 的本地化字符串。
        /// </summary>
        public static string RemoveDeadAndSideEffectFreeCodeUseWithCaution {
            get {
                return ResourceManager.GetString("RemoveDeadAndSideEffectFreeCodeUseWithCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove optional arguments, if possible 的本地化字符串。
        /// </summary>
        public static string RemoveOptionalArgumentsIfPossible {
            get {
                return ResourceManager.GetString("RemoveOptionalArgumentsIfPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show info from debug symbols, if available 的本地化字符串。
        /// </summary>
        public static string ShowInfoFromDebugSymbolsIfAvailable {
            get {
                return ResourceManager.GetString("ShowInfoFromDebugSymbolsIfAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use discards 的本地化字符串。
        /// </summary>
        public static string UseDiscards {
            get {
                return ResourceManager.GetString("UseDiscards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use expression-bodied member syntax for get-only properties 的本地化字符串。
        /// </summary>
        public static string UseExpressionBodiedMemberSyntaxForGetOnlyProperties {
            get {
                return ResourceManager.GetString("UseExpressionBodiedMemberSyntaxForGetOnlyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use extension method syntax 的本地化字符串。
        /// </summary>
        public static string UseExtensionMethodSyntax {
            get {
                return ResourceManager.GetString("UseExtensionMethodSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use implicit conversions between tuple types 的本地化字符串。
        /// </summary>
        public static string UseImplicitConversionsBetweenTupleTypes {
            get {
                return ResourceManager.GetString("UseImplicitConversionsBetweenTupleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use implicit method group conversions 的本地化字符串。
        /// </summary>
        public static string UseImplicitMethodGroupConversions {
            get {
                return ResourceManager.GetString("UseImplicitMethodGroupConversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use lambda syntax, if possible 的本地化字符串。
        /// </summary>
        public static string UseLambdaSyntaxIfPossible {
            get {
                return ResourceManager.GetString("UseLambdaSyntaxIfPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use lifted operators for nullables 的本地化字符串。
        /// </summary>
        public static string UseLiftedOperatorsForNullables {
            get {
                return ResourceManager.GetString("UseLiftedOperatorsForNullables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use LINQ expression syntax 的本地化字符串。
        /// </summary>
        public static string UseLINQExpressionSyntax {
            get {
                return ResourceManager.GetString("UseLINQExpressionSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use named arguments 的本地化字符串。
        /// </summary>
        public static string UseNamedArguments {
            get {
                return ResourceManager.GetString("UseNamedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use non-trailing named arguments 的本地化字符串。
        /// </summary>
        public static string UseNonTrailingNamedArguments {
            get {
                return ResourceManager.GetString("UseNonTrailingNamedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use out variable declarations 的本地化字符串。
        /// </summary>
        public static string UseOutVariableDeclarations {
            get {
                return ResourceManager.GetString("UseOutVariableDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use stackalloc initializer syntax 的本地化字符串。
        /// </summary>
        public static string UseStackallocInitializerSyntax {
            get {
                return ResourceManager.GetString("UseStackallocInitializerSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use string interpolation 的本地化字符串。
        /// </summary>
        public static string UseStringInterpolation {
            get {
                return ResourceManager.GetString("UseStringInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use tuple type syntax 的本地化字符串。
        /// </summary>
        public static string UseTupleTypeSyntax {
            get {
                return ResourceManager.GetString("UseTupleTypeSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use variable names from debug symbols, if available 的本地化字符串。
        /// </summary>
        public static string UseVariableNamesFromDebugSymbolsIfAvailable {
            get {
                return ResourceManager.GetString("UseVariableNamesFromDebugSymbolsIfAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VB-specific options 的本地化字符串。
        /// </summary>
        public static string VBSpecificOptions {
            get {
                return ResourceManager.GetString("VBSpecificOptions", resourceCulture);
            }
        }
    }
}
