//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSharpCode.ILSpy.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICSharpCode.ILSpy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 _About 的本地化字符串。
        /// </summary>
        public static string _About {
            get {
                return ResourceManager.GetString("_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Add To Main List 的本地化字符串。
        /// </summary>
        public static string _AddMainList {
            get {
                return ResourceManager.GetString("_AddMainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Check for Updates 的本地化字符串。
        /// </summary>
        public static string _CheckUpdates {
            get {
                return ResourceManager.GetString("_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Collapse all tree nodes 的本地化字符串。
        /// </summary>
        public static string _CollapseTreeNodes {
            get {
                return ResourceManager.GetString("_CollapseTreeNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string _File {
            get {
                return ResourceManager.GetString("_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string _Help {
            get {
                return ResourceManager.GetString("_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Load Dependencies 的本地化字符串。
        /// </summary>
        public static string _LoadDependencies {
            get {
                return ResourceManager.GetString("_LoadDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _New 的本地化字符串。
        /// </summary>
        public static string _New {
            get {
                return ResourceManager.GetString("_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open... 的本地化字符串。
        /// </summary>
        public static string _Open {
            get {
                return ResourceManager.GetString("_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open Command Line Here 的本地化字符串。
        /// </summary>
        public static string _OpenCommandLineHere {
            get {
                return ResourceManager.GetString("_OpenCommandLineHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open Containing Folder 的本地化字符串。
        /// </summary>
        public static string _OpenContainingFolder {
            get {
                return ResourceManager.GetString("_OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Options... 的本地化字符串。
        /// </summary>
        public static string _Options {
            get {
                return ResourceManager.GetString("_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Reload 的本地化字符串。
        /// </summary>
        public static string _Reload {
            get {
                return ResourceManager.GetString("_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Remove 的本地化字符串。
        /// </summary>
        public static string _Remove {
            get {
                return ResourceManager.GetString("_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Remove Assemblies with load errors 的本地化字符串。
        /// </summary>
        public static string _RemoveAssembliesWithLoadErrors {
            get {
                return ResourceManager.GetString("_RemoveAssembliesWithLoadErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Reset 的本地化字符串。
        /// </summary>
        public static string _Reset {
            get {
                return ResourceManager.GetString("_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resources 的本地化字符串。
        /// </summary>
        public static string _Resources {
            get {
                return ResourceManager.GetString("_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save Code... 的本地化字符串。
        /// </summary>
        public static string _SaveCode {
            get {
                return ResourceManager.GetString("_SaveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Search: 的本地化字符串。
        /// </summary>
        public static string _Search {
            get {
                return ResourceManager.GetString("_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Search for: 的本地化字符串。
        /// </summary>
        public static string _SearchFor {
            get {
                return ResourceManager.GetString("_SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Show debug steps 的本地化字符串。
        /// </summary>
        public static string _ShowDebugSteps {
            get {
                return ResourceManager.GetString("_ShowDebugSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Folding 的本地化字符串。
        /// </summary>
        public static string _ToggleFolding {
            get {
                return ResourceManager.GetString("_ToggleFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _View 的本地化字符串。
        /// </summary>
        public static string _View {
            get {
                return ResourceManager.GetString("_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Window 的本地化字符串。
        /// </summary>
        public static string _Window {
            get {
                return ResourceManager.GetString("_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add preconfigured list... 的本地化字符串。
        /// </summary>
        public static string AddPreconfiguredList {
            get {
                return ResourceManager.GetString("AddPreconfiguredList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add shell integration 的本地化字符串。
        /// </summary>
        public static string AddShellIntegration {
            get {
                return ResourceManager.GetString("AddShellIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will add &quot;{0}&quot; to the registry at &quot;HKCU\Software\Classes\dllfile\shell\Open with ILSpy\command&quot; and &quot;HKCU\Software\Classes\exefile\shell\Open with ILSpy\command&quot; to allow opening .dll and .exe files from the Windows Explorer context menu.
        ///
        ///Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string AddShellIntegrationMessage {
            get {
                return ResourceManager.GetString("AddShellIntegrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 |All Files|*.* 的本地化字符串。
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow multiple instances 的本地化字符串。
        /// </summary>
        public static string AllowMultipleInstances {
            get {
                return ResourceManager.GetString("AllowMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always use braces 的本地化字符串。
        /// </summary>
        public static string AlwaysBraces {
            get {
                return ResourceManager.GetString("AlwaysBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyze 的本地化字符串。
        /// </summary>
        public static string Analyze {
            get {
                return ResourceManager.GetString("Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assemblies 的本地化字符串。
        /// </summary>
        public static string Assemblies {
            get {
                return ResourceManager.GetString("Assemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly 的本地化字符串。
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directory is not empty. File will be overwritten.
        ///Are you sure you want to continue? 的本地化字符串。
        /// </summary>
        public static string AssemblySaveCodeDirectoryNotEmpty {
            get {
                return ResourceManager.GetString("AssemblySaveCodeDirectoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Directory not empty 的本地化字符串。
        /// </summary>
        public static string AssemblySaveCodeDirectoryNotEmptyTitle {
            get {
                return ResourceManager.GetString("AssemblySaveCodeDirectoryNotEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically check for updates every week 的本地化字符串。
        /// </summary>
        public static string AutomaticallyCheckUpdatesEveryWeek {
            get {
                return ResourceManager.GetString("AutomaticallyCheckUpdatesEveryWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base Types 的本地化字符串。
        /// </summary>
        public static string BaseTypes {
            get {
                return ResourceManager.GetString("BaseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C_lone 的本地化字符串。
        /// </summary>
        public static string C_lone {
            get {
                return ResourceManager.GetString("C_lone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity could not be resolved. Cannot analyze entities from missing assembly references. Add the missing reference and try again. 的本地化字符串。
        /// </summary>
        public static string CannotAnalyzeMissingRef {
            get {
                return ResourceManager.GetString("CannotAnalyzeMissingRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check again 的本地化字符串。
        /// </summary>
        public static string CheckAgain {
            get {
                return ResourceManager.GetString("CheckAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking... 的本地化字符串。
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates 的本地化字符串。
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse all tree nodes 的本地化字符串。
        /// </summary>
        public static string CollapseTreeNodes {
            get {
                return ResourceManager.GetString("CollapseTreeNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy error message 的本地化字符串。
        /// </summary>
        public static string CopyErrorMessage {
            get {
                return ResourceManager.GetString("CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy FQ Name 的本地化字符串。
        /// </summary>
        public static string CopyName {
            get {
                return ResourceManager.GetString("CopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Culture 的本地化字符串。
        /// </summary>
        public static string CultureLabel {
            get {
                return ResourceManager.GetString("CultureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DEBUG -- Decompile All 的本地化字符串。
        /// </summary>
        public static string DEBUGDecompile {
            get {
                return ResourceManager.GetString("DEBUGDecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DEBUG -- Decompile 100x 的本地化字符串。
        /// </summary>
        public static string DEBUGDecompile100x {
            get {
                return ResourceManager.GetString("DEBUGDecompile100x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DEBUG -- Disassemble All 的本地化字符串。
        /// </summary>
        public static string DEBUGDisassemble {
            get {
                return ResourceManager.GetString("DEBUGDisassemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DEBUG -- Dump PDB as XML 的本地化字符串。
        /// </summary>
        public static string DEBUGDumpPdb2Xml {
            get {
                return ResourceManager.GetString("DEBUGDumpPdb2Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug Steps 的本地化字符串。
        /// </summary>
        public static string DebugSteps {
            get {
                return ResourceManager.GetString("DebugSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug this step 的本地化字符串。
        /// </summary>
        public static string DebugThisStep {
            get {
                return ResourceManager.GetString("DebugThisStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompiler 的本地化字符串。
        /// </summary>
        public static string Decompiler {
            get {
                return ResourceManager.GetString("Decompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow extension &apos;Add&apos; methods in collection initializer expressions 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_AllowExtensionAddMethodsInCollectionInitializerExpressions {
            get {
                return ResourceManager.GetString("DecompilerSettings.AllowExtensionAddMethodsInCollectionInitializerExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use &apos;ref&apos; extension methods 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_AllowExtensionMethodSyntaxOnRef {
            get {
                return ResourceManager.GetString("DecompilerSettings.AllowExtensionMethodSyntaxOnRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always cast targets of explicit interface implementation calls 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_AlwaysCastTargetsOfExplicitInterfaceImplementationCalls {
            get {
                return ResourceManager.GetString("DecompilerSettings.AlwaysCastTargetsOfExplicitInterfaceImplementationCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always show enum member values 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_AlwaysShowEnumMemberValues {
            get {
                return ResourceManager.GetString("DecompilerSettings.AlwaysShowEnumMemberValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always use braces 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_AlwaysUseBraces {
            get {
                return ResourceManager.GetString("DecompilerSettings.AlwaysUseBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Windows Runtime projections on loaded assemblies 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_ApplyWindowsRuntimeProjectionsOnLoadedAssemblies {
            get {
                return ResourceManager.GetString("DecompilerSettings.ApplyWindowsRuntimeProjectionsOnLoadedAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array initializer expressions 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_ArrayInitializerExpressions {
            get {
                return ResourceManager.GetString("DecompilerSettings.ArrayInitializerExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile async IAsyncEnumerator methods 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_AsyncEnumerator {
            get {
                return ResourceManager.GetString("DecompilerSettings.AsyncEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile ?. and ?[] operators 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileAndOperators {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileAndOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile anonymous methods/lambdas 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileAnonymousMethodsLambdas {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileAnonymousMethodsLambdas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile anonymous types 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileAnonymousTypes {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileAnonymousTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile async methods 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileAsyncMethods {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileAsyncMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile automatic events 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileAutomaticEvents {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileAutomaticEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile automatic properties 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileAutomaticProperties {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileAutomaticProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile await in catch/finally blocks 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileAwaitInCatchFinallyBlocks {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileAwaitInCatchFinallyBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile C# 1.0 &apos;public unsafe fixed int arr[10];&apos; members 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileC10PublicUnsafeFixedIntArr10Members {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileC10PublicUnsafeFixedIntArr10Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile [DecimalConstant(...)] as simple literal values 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileDecimalConstantAsSimpleLiteralValues {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileDecimalConstantAsSimpleLiteralValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile enumerators (yield return) 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileEnumeratorsYieldReturn {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileEnumeratorsYieldReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile expression trees 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileExpressionTrees {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileExpressionTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile use of the &apos;dynamic&apos; type 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DecompileUseOfTheDynamicType {
            get {
                return ResourceManager.GetString("DecompilerSettings.DecompileUseOfTheDynamicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect awaited using and foreach statements 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DetectAsyncUsingAndForeachStatements {
            get {
                return ResourceManager.GetString("DecompilerSettings.DetectAsyncUsingAndForeachStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect foreach statements 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DetectForeachStatements {
            get {
                return ResourceManager.GetString("DecompilerSettings.DetectForeachStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect lock statements 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DetectLockStatements {
            get {
                return ResourceManager.GetString("DecompilerSettings.DetectLockStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect switch on string 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DetectSwitchOnString {
            get {
                return ResourceManager.GetString("DecompilerSettings.DetectSwitchOnString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect tuple comparisons 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DetectTupleComparisons {
            get {
                return ResourceManager.GetString("DecompilerSettings.DetectTupleComparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect using statements 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DetectUsingStatements {
            get {
                return ResourceManager.GetString("DecompilerSettings.DetectUsingStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dictionary initializer expressions 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DictionaryInitializerExpressions {
            get {
                return ResourceManager.GetString("DecompilerSettings.DictionaryInitializerExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transform to do-while, if possible 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_DoWhileStatement {
            get {
                return ResourceManager.GetString("DecompilerSettings.DoWhileStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transform to for, if possible 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_ForStatement {
            get {
                return ResourceManager.GetString("DecompilerSettings.ForStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F#-specific options 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_FSpecificOptions {
            get {
                return ResourceManager.GetString("DecompilerSettings.FSpecificOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include XML documentation comments in the decompiled code 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_IncludeXMLDocumentationCommentsInTheDecompiledCode {
            get {
                return ResourceManager.GetString("DecompilerSettings.IncludeXMLDocumentationCommentsInTheDecompiledCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert using declarations 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_InsertUsingDeclarations {
            get {
                return ResourceManager.GetString("DecompilerSettings.InsertUsingDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Introduce local functions 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_IntroduceLocalFunctions {
            get {
                return ResourceManager.GetString("DecompilerSettings.IntroduceLocalFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Introduce static local functions 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_IntroduceStaticLocalFunctions {
            get {
                return ResourceManager.GetString("DecompilerSettings.IntroduceStaticLocalFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsByRefLikeAttribute should be replaced with &apos;ref&apos; modifiers on structs 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_IsByRefLikeAttributeShouldBeReplacedWithRefModifiersOnStructs {
            get {
                return ResourceManager.GetString("DecompilerSettings.IsByRefLikeAttributeShouldBeReplacedWithRefModifiersOnStructs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsReadOnlyAttribute should be replaced with &apos;readonly&apos;/&apos;in&apos; modifiers on structs/parameters 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_IsReadOnlyAttributeShouldBeReplacedWithReadonlyInModifiersOnStructsParameters {
            get {
                return ResourceManager.GetString("DecompilerSettings.IsReadOnlyAttributeShouldBeReplacedWithReadonlyInModifiersOnSt" +
                        "ructsParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsUnmanagedAttribute on type parameters should be replaced with &apos;unmanaged&apos; constraints 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_IsUnmanagedAttributeOnTypeParametersShouldBeReplacedWithUnmanagedConstraints {
            get {
                return ResourceManager.GetString("DecompilerSettings.IsUnmanagedAttributeOnTypeParametersShouldBeReplacedWithUnmana" +
                        "gedConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use nint/nuint types 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_NativeIntegers {
            get {
                return ResourceManager.GetString("DecompilerSettings.NativeIntegers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nullable reference types 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_NullableReferenceTypes {
            get {
                return ResourceManager.GetString("DecompilerSettings.NullableReferenceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object/collection initializer expressions 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_ObjectCollectionInitializerExpressions {
            get {
                return ResourceManager.GetString("DecompilerSettings.ObjectCollectionInitializerExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_Other {
            get {
                return ResourceManager.GetString("DecompilerSettings.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranges 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_Ranges {
            get {
                return ResourceManager.GetString("DecompilerSettings.Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read-only methods 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_ReadOnlyMethods {
            get {
                return ResourceManager.GetString("DecompilerSettings.ReadOnlyMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove dead and side effect free code (use with caution!) 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_RemoveDeadAndSideEffectFreeCodeUseWithCaution {
            get {
                return ResourceManager.GetString("DecompilerSettings.RemoveDeadAndSideEffectFreeCodeUseWithCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove dead stores (use with caution!) 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_RemoveDeadStores {
            get {
                return ResourceManager.GetString("DecompilerSettings.RemoveDeadStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove optional arguments, if possible 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_RemoveOptionalArgumentsIfPossible {
            get {
                return ResourceManager.GetString("DecompilerSettings.RemoveOptionalArgumentsIfPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Separate local variable declarations and initializers (int x = 5; -&gt; int x; x = 5;), if possible 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_SeparateLocalVariableDeclarations {
            get {
                return ResourceManager.GetString("DecompilerSettings.SeparateLocalVariableDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show info from debug symbols, if available 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_ShowInfoFromDebugSymbolsIfAvailable {
            get {
                return ResourceManager.GetString("DecompilerSettings.ShowInfoFromDebugSymbolsIfAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use discards 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseDiscards {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseDiscards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use expression-bodied member syntax for get-only properties 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseExpressionBodiedMemberSyntaxForGetOnlyProperties {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseExpressionBodiedMemberSyntaxForGetOnlyProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use extension method syntax 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseExtensionMethodSyntax {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseExtensionMethodSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use implicit conversions between tuple types 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseImplicitConversionsBetweenTupleTypes {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseImplicitConversionsBetweenTupleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use implicit method group conversions 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseImplicitMethodGroupConversions {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseImplicitMethodGroupConversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use lambda syntax, if possible 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseLambdaSyntaxIfPossible {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseLambdaSyntaxIfPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use lifted operators for nullables 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseLiftedOperatorsForNullables {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseLiftedOperatorsForNullables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use LINQ expression syntax 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseLINQExpressionSyntax {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseLINQExpressionSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use named arguments 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseNamedArguments {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseNamedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use non-trailing named arguments 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseNonTrailingNamedArguments {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseNonTrailingNamedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use out variable declarations 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseOutVariableDeclarations {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseOutVariableDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use pattern-based fixed statement 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UsePatternBasedFixedStatement {
            get {
                return ResourceManager.GetString("DecompilerSettings.UsePatternBasedFixedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use new SDK style format for generated project files (*.csproj) 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseSdkStyleProjectFormat {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseSdkStyleProjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use stackalloc initializer syntax 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseStackallocInitializerSyntax {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseStackallocInitializerSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use string interpolation 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseStringInterpolation {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseStringInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use throw expressions 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseThrowExpressions {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseThrowExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use tuple type syntax 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseTupleTypeSyntax {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseTupleTypeSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use variable names from debug symbols, if available 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_UseVariableNamesFromDebugSymbolsIfAvailable {
            get {
                return ResourceManager.GetString("DecompilerSettings.UseVariableNamesFromDebugSymbolsIfAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VB-specific options 的本地化字符串。
        /// </summary>
        public static string DecompilerSettings_VBSpecificOptions {
            get {
                return ResourceManager.GetString("DecompilerSettings.VBSpecificOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The settings selected below are applied to the decompiler output in combination with the selection in the language drop-down. Selecting a lower language version in the drop-down will deactivate all selected options of the higher versions. Note that some settings implicitly depend on each other, e.g.: LINQ expressions cannot be introduced without first transforming static calls to extension method calls. 的本地化字符串。
        /// </summary>
        public static string DecompilerSettingsPanelLongText {
            get {
                return ResourceManager.GetString("DecompilerSettingsPanelLongText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompile to new tab 的本地化字符串。
        /// </summary>
        public static string DecompileToNewPanel {
            get {
                return ResourceManager.GetString("DecompileToNewPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompiling... 的本地化字符串。
        /// </summary>
        public static string Decompiling {
            get {
                return ResourceManager.GetString("Decompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependencies 的本地化字符串。
        /// </summary>
        public static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Derived Types 的本地化字符串。
        /// </summary>
        public static string DerivedTypes {
            get {
                return ResourceManager.GetString("DerivedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display 的本地化字符串。
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Code 的本地化字符串。
        /// </summary>
        public static string DisplayCode {
            get {
                return ResourceManager.GetString("DisplayCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font: 的本地化字符串。
        /// </summary>
        public static string DisplaySettingsPanel_Font {
            get {
                return ResourceManager.GetString("DisplaySettingsPanel_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E_xit 的本地化字符串。
        /// </summary>
        public static string E_xit {
            get {
                return ResourceManager.GetString("E_xit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor 的本地化字符串。
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable folding on all blocks in braces 的本地化字符串。
        /// </summary>
        public static string EnableFoldingBlocksBraces {
            get {
                return ResourceManager.GetString("EnableFoldingBlocksBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable word wrap 的本地化字符串。
        /// </summary>
        public static string EnableWordWrap {
            get {
                return ResourceManager.GetString("EnableWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a list name: 的本地化字符串。
        /// </summary>
        public static string EnterListName {
            get {
                return ResourceManager.GetString("EnterListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand member definitions after decompilation 的本地化字符串。
        /// </summary>
        public static string ExpandMemberDefinitionsAfterDecompilation {
            get {
                return ResourceManager.GetString("ExpandMemberDefinitionsAfterDecompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand using declarations after decompilation 的本地化字符串。
        /// </summary>
        public static string ExpandUsingDeclarationsAfterDecompilation {
            get {
                return ResourceManager.GetString("ExpandUsingDeclarationsAfterDecompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folding 的本地化字符串。
        /// </summary>
        public static string Folding {
            get {
                return ResourceManager.GetString("Folding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward 的本地化字符串。
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate portable PDB 的本地化字符串。
        /// </summary>
        public static string GeneratePortable {
            get {
                return ResourceManager.GetString("GeneratePortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide empty metadata tables from tree view 的本地化字符串。
        /// </summary>
        public static string HideEmptyMetadataTables {
            get {
                return ResourceManager.GetString("HideEmptyMetadataTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight matching braces 的本地化字符串。
        /// </summary>
        public static string HighlightMatchingBraces {
            get {
                return ResourceManager.GetString("HighlightMatchingBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ILSpy version  的本地化字符串。
        /// </summary>
        public static string ILSpyVersion {
            get {
                return ResourceManager.GetString("ILSpyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new ILSpy version is available. 的本地化字符串。
        /// </summary>
        public static string ILSpyVersionAvailable {
            get {
                return ResourceManager.GetString("ILSpyVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indentation 的本地化字符串。
        /// </summary>
        public static string Indentation {
            get {
                return ResourceManager.GetString("Indentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent size: 的本地化字符串。
        /// </summary>
        public static string IndentSize {
            get {
                return ResourceManager.GetString("IndentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert using declarations 的本地化字符串。
        /// </summary>
        public static string InsertUsingDeclarations {
            get {
                return ResourceManager.GetString("InsertUsingDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure that you want to delete the selected assembly list? 的本地化字符串。
        /// </summary>
        public static string ListDeleteConfirmation {
            get {
                return ResourceManager.GetString("ListDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A list with the same name was found. 的本地化字符串。
        /// </summary>
        public static string ListExistsAlready {
            get {
                return ResourceManager.GetString("ListExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure that you want to remove all assembly lists and recreate the default assembly lists? 的本地化字符串。
        /// </summary>
        public static string ListsResetConfirmation {
            get {
                return ResourceManager.GetString("ListsResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load assemblies that were loaded in the last instance. 的本地化字符串。
        /// </summary>
        public static string LoadAssembliesThatWereLoadedInTheLastInstance {
            get {
                return ResourceManager.GetString("LoadAssembliesThatWereLoadedInTheLastInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage assembly _lists... 的本地化字符串。
        /// </summary>
        public static string ManageAssembly_Lists {
            get {
                return ResourceManager.GetString("ManageAssembly_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Assembly Lists 的本地化字符串。
        /// </summary>
        public static string ManageAssemblyLists {
            get {
                return ResourceManager.GetString("ManageAssemblyLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Misc 的本地化字符串。
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation 的本地化字符串。
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation failed because the target is hidden or a compiler-generated class.\n
        ///Please disable all filters that might hide the item (i.e. activate &quot;View &gt; Show internal types and members&quot;) and try again. 的本地化字符串。
        /// </summary>
        public static string NavigationFailed {
            get {
                return ResourceManager.GetString("NavigationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New list 的本地化字符串。
        /// </summary>
        public static string NewList {
            get {
                return ResourceManager.GetString("NewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Tab 的本地化字符串。
        /// </summary>
        public static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nuget Package Browser 的本地化字符串。
        /// </summary>
        public static string NugetPackageBrowser {
            get {
                return ResourceManager.GetString("NugetPackageBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Explorer 的本地化字符串。
        /// </summary>
        public static string OpenExplorer {
            get {
                return ResourceManager.GetString("OpenExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open From GAC 的本地化字符串。
        /// </summary>
        public static string OpenFrom {
            get {
                return ResourceManager.GetString("OpenFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open from _GAC... 的本地化字符串。
        /// </summary>
        public static string OpenFrom_GAC {
            get {
                return ResourceManager.GetString("OpenFrom_GAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Delete 的本地化字符串。
        /// </summary>
        public static string OpenListDialog__Delete {
            get {
                return ResourceManager.GetString("OpenListDialog__Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open 的本地化字符串。
        /// </summary>
        public static string OpenListDialog__Open {
            get {
                return ResourceManager.GetString("OpenListDialog__Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other options 的本地化字符串。
        /// </summary>
        public static string OtherOptions {
            get {
                return ResourceManager.GetString("OtherOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Resources 的本地化字符串。
        /// </summary>
        public static string OtherResources {
            get {
                return ResourceManager.GetString("OtherResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 for ex. property getter/setter access. To get optimal decompilation results, please manually add the missing references to the list of loaded assemblies. 的本地化字符串。
        /// </summary>
        public static string PropertyManuallyMissingReferencesListLoadedAssemblies {
            get {
                return ResourceManager.GetString("PropertyManuallyMissingReferencesListLoadedAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Public Key Token 的本地化字符串。
        /// </summary>
        public static string PublicToken {
            get {
                return ResourceManager.GetString("PublicToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R_ename 的本地化字符串。
        /// </summary>
        public static string R_ename {
            get {
                return ResourceManager.GetString("R_ename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference Name 的本地化字符串。
        /// </summary>
        public static string ReferenceName {
            get {
                return ResourceManager.GetString("ReferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 References 的本地化字符串。
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload all assemblies 的本地化字符串。
        /// </summary>
        public static string RefreshCommand_ReloadAssemblies {
            get {
                return ResourceManager.GetString("RefreshCommand_ReloadAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload all assemblies 的本地化字符串。
        /// </summary>
        public static string ReloadAssemblies {
            get {
                return ResourceManager.GetString("ReloadAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove dead and side effect free code 的本地化字符串。
        /// </summary>
        public static string RemoveDeadSideEffectFreeCode {
            get {
                return ResourceManager.GetString("RemoveDeadSideEffectFreeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove shell integration 的本地化字符串。
        /// </summary>
        public static string RemoveShellIntegration {
            get {
                return ResourceManager.GetString("RemoveShellIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will remove &quot;{0}&quot; from the registry at &quot;HKCU\Software\Classes\dllfile\shell\Open with ILSpy\command&quot; and &quot;HKCU\Software\Classes\exefile\shell\Open with ILSpy\command&quot;.
        ///
        ///Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string RemoveShellIntegrationMessage {
            get {
                return ResourceManager.GetString("RemoveShellIntegrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename list 的本地化字符串。
        /// </summary>
        public static string RenameList {
            get {
                return ResourceManager.GetString("RenameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to defaults 的本地化字符串。
        /// </summary>
        public static string ResetToDefaults {
            get {
                return ResourceManager.GetString("ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to load the default settings for the active page? 的本地化字符串。
        /// </summary>
        public static string ResetToDefaultsConfirmationMessage {
            get {
                return ResourceManager.GetString("ResetToDefaultsConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resources file (*.resources)|*.resources|Resource XML file|*.resx 的本地化字符串。
        /// </summary>
        public static string ResourcesFileFilter {
            get {
                return ResourceManager.GetString("ResourcesFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Code 的本地化字符串。
        /// </summary>
        public static string SaveCode {
            get {
                return ResourceManager.GetString("SaveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search... 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search aborted, more than 1000 results found. 的本地化字符串。
        /// </summary>
        public static string SearchAbortedMoreThan1000ResultsFound {
            get {
                return ResourceManager.GetString("SearchAbortedMoreThan1000ResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search (Ctrl+Shift+F or Ctrl+E) 的本地化字符串。
        /// </summary>
        public static string SearchCtrlShiftFOrCtrlE {
            get {
                return ResourceManager.GetString("SearchCtrlShiftFOrCtrlE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching... 的本地化字符串。
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Microsoft Docs... 的本地化字符串。
        /// </summary>
        public static string SearchMSDN {
            get {
                return ResourceManager.GetString("SearchMSDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string SearchPane_Search {
            get {
                return ResourceManager.GetString("SearchPane_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select assemblies to open: 的本地化字符串。
        /// </summary>
        public static string SelectAssembliesOpen {
            get {
                return ResourceManager.GetString("SelectAssembliesOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a list of assemblies 的本地化字符串。
        /// </summary>
        public static string SelectAssemblyListDropdownTooltip {
            get {
                return ResourceManager.GetString("SelectAssemblyListDropdownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select language to decompile to 的本地化字符串。
        /// </summary>
        public static string SelectLanguageDropdownTooltip {
            get {
                return ResourceManager.GetString("SelectLanguageDropdownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a list: 的本地化字符串。
        /// </summary>
        public static string SelectList {
            get {
                return ResourceManager.GetString("SelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select version of language to output 的本地化字符串。
        /// </summary>
        public static string SelectVersionDropdownTooltip {
            get {
                return ResourceManager.GetString("SelectVersionDropdownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shell 的本地化字符串。
        /// </summary>
        public static string Shell {
            get {
                return ResourceManager.GetString("Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show _all types and members 的本地化字符串。
        /// </summary>
        public static string Show_allTypesAndMembers {
            get {
                return ResourceManager.GetString("Show_allTypesAndMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show public, private and internal 的本地化字符串。
        /// </summary>
        public static string Show_internalTypesMembers {
            get {
                return ResourceManager.GetString("Show_internalTypesMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show only _public types and members 的本地化字符串。
        /// </summary>
        public static string Show_publiconlyTypesMembers {
            get {
                return ResourceManager.GetString("Show_publiconlyTypesMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show all types and members 的本地化字符串。
        /// </summary>
        public static string ShowAllTypesAndMembers {
            get {
                return ResourceManager.GetString("ShowAllTypesAndMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show assembly load log 的本地化字符串。
        /// </summary>
        public static string ShowAssemblyLoad {
            get {
                return ResourceManager.GetString("ShowAssemblyLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowChildIndexInBlock 的本地化字符串。
        /// </summary>
        public static string ShowChildIndexInBlock {
            get {
                return ResourceManager.GetString("ShowChildIndexInBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show XML documentation in decompiled code 的本地化字符串。
        /// </summary>
        public static string ShowDocumentationDecompiledCode {
            get {
                return ResourceManager.GetString("ShowDocumentationDecompiledCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowILRanges 的本地化字符串。
        /// </summary>
        public static string ShowILRanges {
            get {
                return ResourceManager.GetString("ShowILRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show info from debug symbols, if available 的本地化字符串。
        /// </summary>
        public static string ShowInfoFromDebugSymbolsAvailable {
            get {
                return ResourceManager.GetString("ShowInfoFromDebugSymbolsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show public, private and internal 的本地化字符串。
        /// </summary>
        public static string ShowInternalTypesMembers {
            get {
                return ResourceManager.GetString("ShowInternalTypesMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show line numbers 的本地化字符串。
        /// </summary>
        public static string ShowLineNumbers {
            get {
                return ResourceManager.GetString("ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show metadata tokens 的本地化字符串。
        /// </summary>
        public static string ShowMetadataTokens {
            get {
                return ResourceManager.GetString("ShowMetadataTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show metadata tokens in base 10 的本地化字符串。
        /// </summary>
        public static string ShowMetadataTokensInBase10 {
            get {
                return ResourceManager.GetString("ShowMetadataTokensInBase10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show only public types and members 的本地化字符串。
        /// </summary>
        public static string ShowPublicOnlyTypesMembers {
            get {
                return ResourceManager.GetString("ShowPublicOnlyTypesMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show state after this step 的本地化字符串。
        /// </summary>
        public static string ShowStateAfterThisStep {
            get {
                return ResourceManager.GetString("ShowStateAfterThisStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show state before this step 的本地化字符串。
        /// </summary>
        public static string ShowStateBeforeThisStep {
            get {
                return ResourceManager.GetString("ShowStateBeforeThisStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size: 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort assembly _list by name 的本地化字符串。
        /// </summary>
        public static string SortAssembly_listName {
            get {
                return ResourceManager.GetString("SortAssembly_listName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort assembly list by name 的本地化字符串。
        /// </summary>
        public static string SortAssemblyListName {
            get {
                return ResourceManager.GetString("SortAssemblyListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort results by fitness 的本地化字符串。
        /// </summary>
        public static string SortResultsFitness {
            get {
                return ResourceManager.GetString("SortResultsFitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stand by... 的本地化字符串。
        /// </summary>
        public static string StandBy {
            get {
                return ResourceManager.GetString("StandBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String Table 的本地化字符串。
        /// </summary>
        public static string StringTable {
            get {
                return ResourceManager.GetString("StringTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tab size: 的本地化字符串。
        /// </summary>
        public static string TabSize {
            get {
                return ResourceManager.GetString("TabSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle All Folding 的本地化字符串。
        /// </summary>
        public static string ToggleFolding {
            get {
                return ResourceManager.GetString("ToggleFolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No update for ILSpy found. 的本地化字符串。
        /// </summary>
        public static string UpdateILSpyFound {
            get {
                return ResourceManager.GetString("UpdateILSpyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UseFieldSugar 的本地化字符串。
        /// </summary>
        public static string UseFieldSugar {
            get {
                return ResourceManager.GetString("UseFieldSugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UseLogicOperationSugar 的本地化字符串。
        /// </summary>
        public static string UseLogicOperationSugar {
            get {
                return ResourceManager.GetString("UseLogicOperationSugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use tabs instead of spaces 的本地化字符串。
        /// </summary>
        public static string UseTabsInsteadOfSpaces {
            get {
                return ResourceManager.GetString("UseTabsInsteadOfSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using the latest release. 的本地化字符串。
        /// </summary>
        public static string UsingLatestRelease {
            get {
                return ResourceManager.GetString("UsingLatestRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using a nightly build newer than the latest release. 的本地化字符串。
        /// </summary>
        public static string UsingNightlyBuildNewerThanLatestRelease {
            get {
                return ResourceManager.GetString("UsingNightlyBuildNewerThanLatestRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value (as string) 的本地化字符串。
        /// </summary>
        public static string ValueString {
            get {
                return ResourceManager.GetString("ValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use variable names from debug symbols, if available 的本地化字符串。
        /// </summary>
        public static string VariableNamesFromDebugSymbolsAvailable {
            get {
                return ResourceManager.GetString("VariableNamesFromDebugSymbolsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version {0} is available. 的本地化字符串。
        /// </summary>
        public static string VersionAvailable {
            get {
                return ResourceManager.GetString("VersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: This assembly is marked as &apos;reference assembly&apos;, which means that it only contains metadata and no executable code. 的本地化字符串。
        /// </summary>
        public static string WarningAsmMarkedRef {
            get {
                return ResourceManager.GetString("WarningAsmMarkedRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Some assembly references could not be resolved automatically. This might lead to incorrect decompilation of some parts, 的本地化字符串。
        /// </summary>
        public static string WarningSomeAssemblyReference {
            get {
                return ResourceManager.GetString("WarningSomeAssemblyReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search for t:TypeName, m:Member or c:Constant; use exact match (=term), &apos;should not contain&apos; (-term) or &apos;must contain&apos; (+term); use /reg(ular)?Ex(pressions)?/ or both - t:/Type(Name)?/... 的本地化字符串。
        /// </summary>
        public static string WatermarkText {
            get {
                return ResourceManager.GetString("WatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Close all documents 的本地化字符串。
        /// </summary>
        public static string Window_CloseAllDocuments {
            get {
                return ResourceManager.GetString("Window_CloseAllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Reset layout 的本地化字符串。
        /// </summary>
        public static string Window_ResetLayout {
            get {
                return ResourceManager.GetString("Window_ResetLayout", resourceCulture);
            }
        }
    }
}
